name: Go

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        go build -ldflags "-s -w -X main.BuildVersion=$(git describe --tags --always --match 'v*') -X main.BuildTime=$(date +%s)" .

    - name: Release Continuous
      uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/v2'
      with:
        prerelease: true
        draft: false
        automatic_release_tag: v2-continuous
        title: v2 (continuous)
        files: |
          zap
        repo_token: ${{ secrets.GITHUB_TOKEN }}
